name: UpdateTheCache

on:
  workflow_dispatch:

jobs:
  run-selected-test:
    name: 'update main maven cache'
    runs-on: ubuntu-latest

    steps:
      - name: Git clone
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'corretto'
          java-version: '17'
          cache: 'maven'

      - name: Maven compile
        run: mvn -Dtest=*Header* test
